### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by shaansubbaiah** [shaansubbaiah/Portfolio#42]
- [x] Handle links in repository description
- [x] Lighter repo img bg
- [x] Locally serve repo imgs
- [x] Use Sharp to compress images
- [x] Other issues mentioned in Lighthouse
